---
- name: "Install node and npm"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "Install n"
  become: true
  npm:
    name: n
    global: true
    production: true

- name: "Switch node to version v13.8.0"
  become: true
  shell: n 13.8.0

- name: "Install PM2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present