---
- name: "Create dir"
  shell: mkdir ~/backend

- name: "Sync artifact"
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend

- name: "Install artifact"
  npm:
    path: ~/backend
    production: true
    global: true

- name: "Start node app using pm2"
  shell: cd ~/backend && pm2 stop all; pm2 start npm -- run start