version: 2.1

orbs:
  slack: circleci/slack@4.10.1

commands:
  notify_failure:
    steps:
      - slack/notify:
          event: fail
          mentions: "@Ahmed_Ibrahim"
          template: basic_fail_1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Fail on purpose
          command: return 1
      - run:
          name: Front-end build
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
      - notify_failure

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - notify_failure
  
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end test
          command:  |
            cd frontend
            npm install
            npm run test
      - notify_failure

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end test
          command:  |
            cd backend
            npm install
            npm run test
      - notify_failure
  
  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Front-end audit
          command:  |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
      - notify_failure

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end audit
          command:  |
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit fix --force
            npm audit --audit-level=critical
      - notify_failure

workflows:
  default:
    jobs:
      - build-frontend:
          context: Slack-Notifications-Udacity-Project
      - build-backend:
          context: Slack-Notifications-Udacity-Project
      - test-frontend:
          requires:
            - build-frontend
          context: Slack-Notifications-Udacity-Project
      - test-backend:
          requires:
            - build-backend
          context: Slack-Notifications-Udacity-Project
      - scan-frontend:
          requires:
            - build-frontend
          context: Slack-Notifications-Udacity-Project
      - scan-backend:
          requires:
            - build-backend
          context: Slack-Notifications-Udacity-Project